version: '3.8'

services:
  email-classifier:
    build: .
    ports:
      - "7860:7860"
    environment:
      - STREAMLIT_SERVER_PORT=7860
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    volumes:
      # Mount models directory for faster development
      - ./models:/app/models:ro
      # Mount icons directory
      - ./icons:/app/icons:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - email-classifier
    restart: unless-stopped
    profiles:
      - production
